//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace NinjaTasks.App.Droid
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Attr
        {
            
            public const int TaskListsListStyle = 0x7f010000;
            
            public const int TaskListsListRowStyle = 0x7f010001;
            
            public const int TaskListsListRowSecondaryStyle = 0x7f010002;
            
            public const int TaskListStyle = 0x7f010003;
            
            public const int ic_action_add_list = 0x7f010004;
            
            public const int ic_action_list = 0x7f010005;
            
            public const int ic_action_share = 0x7f010006;
            
            public const int ic_action_settings = 0x7f010007;
            
            public const int ic_action_toggle_completed = 0x7f010008;
            
            public const int btn_delete = 0x7f010009;
            
            public const int ptrHeaderStyle = 0x7f01000a;
            
            public const int ptrHeaderBackground = 0x7f01000b;
            
            public const int ptrHeaderHeight = 0x7f01000c;
            
            public const int ptrHeaderTitleTextAppearance = 0x7f01000d;
            
            public const int ptrProgressBarColor = 0x7f01000e;
            
            public const int ptrPullText = 0x7f01000f;
            
            public const int ptrRefreshingText = 0x7f010010;
            
            public const int ptrReleaseText = 0x7f010011;
            
            public const int MvxBind = 0x7f010012;
            
            public const int MvxLang = 0x7f010013;
            
            public const int MvxTemplate = 0x7f010014;
            
            public const int MvxItemTemplate = 0x7f010015;
            
            public const int MvxDropDownItemTemplate = 0x7f010016;
            
            public const int GroupItemTemplate = 0x7f010017;
            
            public const int MvxSource = 0x7f010018;
            
            public const int navigation_refresh = 0x7f010019;
            
            public const int action_search = 0x7f01001a;
            
            public const int action_settings = 0x7f01001b;
            
            public const int action_toggle_completed = 0x7f01001c;
            
            public const int content_new = 0x7f01001d;
            
            public const int content_discard = 0x7f01001e;
            
            public const int content_copy = 0x7f01001f;
            
            public const int content_paste = 0x7f010020;
            
            public const int content_undo = 0x7f010021;
            
            public const int content_remove = 0x7f010022;
            
            public const int ab_cancel = 0x7f010023;
            
            public const int device_access_secure = 0x7f010024;
            
            public const int device_access_not_secure = 0x7f010025;
            
            public const int social_share = 0x7f010026;
            
            public const int navigation_accept = 0x7f010027;
            
            public const int my_list_selector = 0x7f010028;
            
            public const int my_list_background = 0x7f010029;
            
            public const int editorBackgroundColor = 0x7f01002a;
            
            public const int ActionBarDropDownItem = 0x7f01002b;
            
            public const int btn_default_selector = 0x7f01002c;
            
            public const int img_default_selector = 0x7f01002d;
            
            public const int SpinnerStyle = 0x7f01002e;
            
            public const int expander_open_holo = 0x7f01002f;
            
            public const int expander_close_holo = 0x7f010030;
            
            public const int list_divider_holo = 0x7f010031;
            
            public const int viewpager_bg = 0x7f010032;
            
            public const int textColorPrimary = 0x7f010033;
            
            public const int textColorSecondary = 0x7f010034;
            
            public const int list_item_card_background = 0x7f010035;
            
            public const int labelAddItemTextColor = 0x7f010036;
            
            public const int body_new = 0x7f010037;
            
            public const int body_remove = 0x7f010038;
            
            public const int body_delete = 0x7f010039;
            
            public const int drag_handle_color = 0x7f01003a;
            
            public const int max = 0x7f01003b;
            
            public const int min = 0x7f01003c;
            
            public const int unitsLeft = 0x7f01003d;
            
            public const int unitsRight = 0x7f01003e;
            
            public const int units = 0x7f01003f;
            
            public const int summary = 0x7f010040;
            
            public const int interval = 0x7f010041;
            
            public const int TaskListItem = 0x7f010042;
            
            public const int ListDividerStyle = 0x7f010043;
            
            public const int ListMarginStyle = 0x7f010044;
            
            public const int ListHeaderSize = 0x7f010045;
            
            public const int linkify = 0x7f010046;
            
            public const int styledText = 0x7f010047;
            
            public const int titleRelativeSize = 0x7f010048;
            
            public const int titleFontFamily = 0x7f010049;
            
            public const int titleFontStyle = 0x7f01004a;
            
            public const int bodyFontFamily = 0x7f01004b;
            
            public const int secondaryColor = 0x7f01004c;
            
            public const int isDialog = 0x7f01004d;
        }
        
        public sealed class Drawable
        {
            
            public const int action_about_dark = 0x7f020000;
            
            public const int action_help_dark = 0x7f020001;
            
            public const int action_search_dark = 0x7f020002;
            
            public const int action_search_light = 0x7f020003;
            
            public const int action_settings_dark = 0x7f020004;
            
            public const int action_settings_light = 0x7f020005;
            
            public const int action_toggle_completed_dark = 0x7f020006;
            
            public const int action_toogle_completed_light = 0x7f020007;
            
            public const int arrow_list_selector = 0x7f020008;
            
            public const int background_holo_dark = 0x7f020009;
            
            public const int btn_check_off_holo_dark = 0x7f02000a;
            
            public const int btn_check_off_holo_light = 0x7f02000b;
            
            public const int btn_check_off_pressed_holo_dark = 0x7f02000c;
            
            public const int btn_check_off_pressed_holo_light = 0x7f02000d;
            
            public const int btn_check_on_holo_dark = 0x7f02000e;
            
            public const int btn_check_on_holo_light = 0x7f02000f;
            
            public const int btn_check_on_pressed_holo_dark = 0x7f020010;
            
            public const int btn_check_on_pressed_holo_light = 0x7f020011;
            
            public const int btn_check_selector_dark = 0x7f020012;
            
            public const int btn_check_selector_light = 0x7f020013;
            
            public const int btn_default_disabled_focused_holo_dark = 0x7f020014;
            
            public const int btn_default_focused_holo_dark = 0x7f020015;
            
            public const int btn_default_pressed_holo_dark = 0x7f020016;
            
            public const int btn_default_selector_dark = 0x7f020017;
            
            public const int btn_default_selector_light = 0x7f020018;
            
            public const int btn_delete_dark = 0x7f020019;
            
            public const int btn_delete_light = 0x7f02001a;
            
            public const int btn_toggle = 0x7f02001b;
            
            public const int btn_toggle_bg = 0x7f02001c;
            
            public const int btn_toggle_off_normal = 0x7f02001d;
            
            public const int btn_toggle_off_normal_light = 0x7f02001e;
            
            public const int btn_toggle_off_pressed = 0x7f02001f;
            
            public const int btn_toggle_off_pressed_light = 0x7f020020;
            
            public const int btn_toggle_on_normal = 0x7f020021;
            
            public const int btn_toggle_on_pressed = 0x7f020022;
            
            public const int card_dark = 0x7f020023;
            
            public const int card_light = 0x7f020024;
            
            public const int check_selector_dark = 0x7f020025;
            
            public const int checkmark = 0x7f020026;
            
            public const int content_copy_dark = 0x7f020027;
            
            public const int content_copy_light = 0x7f020028;
            
            public const int content_discard_dark = 0x7f020029;
            
            public const int content_discard_light = 0x7f02002a;
            
            public const int content_new_dark = 0x7f02002b;
            
            public const int content_new_light = 0x7f02002c;
            
            public const int content_paste_dark = 0x7f02002d;
            
            public const int content_paste_light = 0x7f02002e;
            
            public const int content_remove_dark = 0x7f02002f;
            
            public const int content_remove_light = 0x7f020030;
            
            public const int dark_widget_bg = 0x7f020031;
            
            public const int dark_widget_header = 0x7f020032;
            
            public const int darkening_rounded_corners = 0x7f020033;
            
            public const int delete = 0x7f020034;
            
            public const int device_access_alarms_dark = 0x7f020035;
            
            public const int device_access_brightness_medium_dark = 0x7f020036;
            
            public const int device_access_not_secure_dark = 0x7f020037;
            
            public const int device_access_not_secure_light = 0x7f020038;
            
            public const int device_access_secure_dark = 0x7f020039;
            
            public const int device_access_secure_light = 0x7f02003a;
            
            public const int divider_line = 0x7f02003b;
            
            public const int divider_line2 = 0x7f02003c;
            
            public const int divider_line3 = 0x7f02003d;
            
            public const int drawer_shadow_dark = 0x7f02003e;
            
            public const int drawer_shadow_light = 0x7f02003f;
            
            public const int expander_close_disabled_holo_dark = 0x7f020040;
            
            public const int expander_close_disabled_holo_light = 0x7f020041;
            
            public const int expander_close_holo_dark = 0x7f020042;
            
            public const int expander_close_holo_light = 0x7f020043;
            
            public const int expander_open_holo_dark = 0x7f020044;
            
            public const int expander_open_holo_light = 0x7f020045;
            
            public const int filled_box_30 = 0x7f020046;
            
            public const int filled_box_black = 0x7f020047;
            
            public const int greyable_toggle_off_bg = 0x7f020048;
            
            public const int greyable_toggle_on_bg = 0x7f020049;
            
            public const int ic_ab_back_holo_dark_am = 0x7f02004a;
            
            public const int ic_action_add_list_dark = 0x7f02004b;
            
            public const int ic_action_add_list_light = 0x7f02004c;
            
            public const int ic_action_big_expander_close_dark = 0x7f02004d;
            
            public const int ic_action_big_expander_close_light = 0x7f02004e;
            
            public const int ic_action_big_expander_open_dark = 0x7f02004f;
            
            public const int ic_action_big_expander_open_light = 0x7f020050;
            
            public const int ic_action_device_access_sd_storage_dark = 0x7f020051;
            
            public const int ic_action_list_dark = 0x7f020052;
            
            public const int ic_action_list_light = 0x7f020053;
            
            public const int ic_action_list_prefs_dark = 0x7f020054;
            
            public const int ic_action_share_dark = 0x7f020055;
            
            public const int ic_action_share_light = 0x7f020056;
            
            public const int ic_action_toggle_completed_dark = 0x7f020057;
            
            public const int ic_action_toogle_completed_light = 0x7f020058;
            
            public const int ic_add_alarm_dark = 0x7f020059;
            
            public const int ic_alarm = 0x7f02005a;
            
            public const int ic_alarm_add_blue = 0x7f02005b;
            
            public const int ic_alarm_add_red = 0x7f02005c;
            
            public const int ic_alarm_red = 0x7f02005d;
            
            public const int ic_delete_black_18dp = 0x7f02005e;
            
            public const int ic_delete_black_24dp = 0x7f02005f;
            
            public const int ic_delete_black_36dp = 0x7f020060;
            
            public const int ic_delete_black_48dp = 0x7f020061;
            
            public const int ic_delete_white_18dp = 0x7f020062;
            
            public const int ic_delete_white_24dp = 0x7f020063;
            
            public const int ic_delete_white_36dp = 0x7f020064;
            
            public const int ic_delete_white_48dp = 0x7f020065;
            
            public const int ic_drawer_dark = 0x7f020066;
            
            public const int ic_drawer_light = 0x7f020067;
            
            public const int ic_error_outline_black_18dp = 0x7f020068;
            
            public const int ic_error_outline_black_24dp = 0x7f020069;
            
            public const int ic_error_outline_black_36dp = 0x7f02006a;
            
            public const int ic_error_outline_black_48dp = 0x7f02006b;
            
            public const int ic_error_outline_white_18dp = 0x7f02006c;
            
            public const int ic_error_outline_white_24dp = 0x7f02006d;
            
            public const int ic_error_outline_white_36dp = 0x7f02006e;
            
            public const int ic_error_outline_white_48dp = 0x7f02006f;
            
            public const int ic_launcher = 0x7f020070;
            
            public const int ic_location = 0x7f020071;
            
            public const int ic_location_red = 0x7f020072;
            
            public const int ic_playlist_add_black_48dp = 0x7f020073;
            
            public const int ic_playlist_add_white_48dp = 0x7f020074;
            
            public const int ic_playlist_add_white_48dp_30 = 0x7f020075;
            
            public const int ic_playlist_add_white_48dp_60 = 0x7f020076;
            
            public const int ic_settings_black_48dp = 0x7f020077;
            
            public const int ic_settings_white_48dp = 0x7f020078;
            
            public const int ic_settings_white_48dp_60 = 0x7f020079;
            
            public const int ic_stat_notification_edit = 0x7f02007a;
            
            public const int ic_stat_snooze = 0x7f02007b;
            
            public const int img_default_selector_dark = 0x7f02007c;
            
            public const int img_default_selector_light = 0x7f02007d;
            
            public const int japanese_paper_tiled = 0x7f02007e;
            
            public const int japanese_paper_yellow = 0x7f02007f;
            
            public const int JapanesePaper = 0x7f020080;
            
            public const int light_border = 0x7f020081;
            
            public const int light_widget_header = 0x7f020082;
            
            public const int list_30 = 0x7f020083;
            
            public const int list_activated_holo = 0x7f020084;
            
            public const int list_arrow_activated_holo = 0x7f020085;
            
            public const int list_arrow_focused_holo = 0x7f020086;
            
            public const int list_arrow_pressed_holo = 0x7f020087;
            
            public const int list_arrow_selected_holo = 0x7f020088;
            
            public const int list_black = 0x7f020089;
            
            public const int list_div_top_btm_gmail_widget_holo = 0x7f02008a;
            
            public const int list_divider_holo_dark = 0x7f02008b;
            
            public const int list_divider_holo_light = 0x7f02008c;
            
            public const int list_pressed_holo_dark = 0x7f02008d;
            
            public const int list_read_holo = 0x7f02008e;
            
            public const int navigation_accept_dark = 0x7f02008f;
            
            public const int navigation_accept_light = 0x7f020090;
            
            public const int navigation_refresh_dark = 0x7f020091;
            
            public const int navigation_refresh_light = 0x7f020092;
            
            public const int plus_math_10 = 0x7f020093;
            
            public const int plus_math_30 = 0x7f020094;
            
            public const int plus_math_black = 0x7f020095;
            
            public const int preview_ori_portrait = 0x7f020096;
            
            public const int ptr_progress_horizontal_holo_center = 0x7f020097;
            
            public const int ptr_progress_indeterminate_horizontal_holo = 0x7f020098;
            
            public const int ptr_progress_primary_holo = 0x7f020099;
            
            public const int ptr_progressbar_indeterminate_holo1 = 0x7f02009a;
            
            public const int ptr_progressbar_indeterminate_holo2 = 0x7f02009b;
            
            public const int ptr_progressbar_indeterminate_holo3 = 0x7f02009c;
            
            public const int ptr_progressbar_indeterminate_holo4 = 0x7f02009d;
            
            public const int ptr_progressbar_indeterminate_holo5 = 0x7f02009e;
            
            public const int ptr_progressbar_indeterminate_holo6 = 0x7f02009f;
            
            public const int ptr_progressbar_indeterminate_holo7 = 0x7f0200a0;
            
            public const int ptr_progressbar_indeterminate_holo8 = 0x7f0200a1;
            
            public const int search_padded = 0x7f0200a2;
            
            public const int selected_item_background = 0x7f0200a3;
            
            public const int selected_item_background_70 = 0x7f0200a4;
            
            public const int selected_item_background_rounded = 0x7f0200a5;
            
            public const int selected_item_background_rounded_70 = 0x7f0200a6;
            
            public const int shadow_vertical = 0x7f0200a7;
            
            public const int social_share_dark = 0x7f0200a8;
            
            public const int social_share_light = 0x7f0200a9;
            
            public const int splash = 0x7f0200aa;
            
            public const int splash_non_stretch = 0x7f0200ab;
            
            public const int star_10 = 0x7f0200ac;
            
            public const int star_20 = 0x7f0200ad;
            
            public const int star_30 = 0x7f0200ae;
            
            public const int star_black = 0x7f0200af;
            
            public const int star_button_drawable = 0x7f0200b0;
            
            public const int star_red = 0x7f0200b1;
            
            public const int star_small_10 = 0x7f0200b2;
            
            public const int star_small_red = 0x7f0200b3;
            
            public const int tasklist_item_blackclassic_bg = 0x7f0200b4;
            
            public const int tasklist_item_darkcard_bg = 0x7f0200b5;
            
            public const int tasklist_item_lightcard_bg = 0x7f0200b6;
            
            public const int tasklist_item_lightclassic_bg = 0x7f0200b7;
            
            public const int tasklistrow_background = 0x7f0200b8;
            
            public const int tasklistslistrow_background = 0x7f0200b9;
            
            public const int taskwarrior_logo = 0x7f0200ba;
            
            public const int transparent = 0x7f0200bb;
            
            public const int ui_bluetooth_proxy = 0x7f0200bc;
            
            public const int ui_refresh = 0x7f0200bd;
            
            public const int actionbar_background = 0x7f0200be;
        }
        
        public sealed class Layout
        {
            
            public const int AppView = 0x7f030000;
            
            public const int ConfigureAccounts = 0x7f030001;
            
            public const int ConfigureAccountsAccountRow = 0x7f030002;
            
            public const int default_header = 0x7f030003;
            
            public const int EditList = 0x7f030004;
            
            public const int LogEntry = 0x7f030005;
            
            public const int MainLayout = 0x7f030006;
            
            public const int SelectRemoteDeviceItem = 0x7f030007;
            
            public const int SelectRemoteDeviceView = 0x7f030008;
            
            public const int SplashScreen = 0x7f030009;
            
            public const int TaskDetails = 0x7f03000a;
            
            public const int TaskList = 0x7f03000b;
            
            public const int TaskListRow = 0x7f03000c;
            
            public const int TaskListsList = 0x7f03000d;
            
            public const int TaskListsListAdd = 0x7f03000e;
            
            public const int TaskListsListRow = 0x7f03000f;
            
            public const int TaskWarriorAccountView = 0x7f030010;
        }
        
        public sealed class Anim
        {
            
            public const int activity_slide_in_left = 0x7f040000;
            
            public const int activity_slide_in_right = 0x7f040001;
            
            public const int activity_slide_in_right_full = 0x7f040002;
            
            public const int activity_slide_out_left = 0x7f040003;
            
            public const int activity_slide_out_right = 0x7f040004;
            
            public const int activity_slide_out_right_full = 0x7f040005;
            
            public const int cycle_7 = 0x7f040006;
            
            public const int shake = 0x7f040007;
            
            public const int slide_in_bottom = 0x7f040008;
            
            public const int slide_in_top = 0x7f040009;
            
            public const int slide_out_bottom = 0x7f04000a;
            
            public const int slide_out_top = 0x7f04000b;
        }
        
        public sealed class Xml
        {
            
            public const int account_authenticator = 0x7f050000;
            
            public const int account_prefs = 0x7f050001;
            
            public const int general_settings = 0x7f050002;
            
            public const int sync_ninjatasks = 0x7f050003;
            
            public const int sync_nonsenseapps_notepad = 0x7f050004;
        }
        
        public sealed class Dimen
        {
            
            public const int activity_vertical_margin = 0x7f060000;
            
            public const int activity_horizontal_margin = 0x7f060001;
            
            public const int btn_size = 0x7f060002;
            
            public const int one = 0x7f060003;
            
            public const int two = 0x7f060004;
            
            public const int three = 0x7f060005;
            
            public const int four = 0x7f060006;
            
            public const int five = 0x7f060007;
            
            public const int six = 0x7f060008;
            
            public const int minus_three = 0x7f060009;
            
            public const int drag_grip_ridge_size = 0x7f06000a;
            
            public const int drag_grip_ridge_gap = 0x7f06000b;
            
            public const int drag_grip_width = 0x7f06000c;
            
            public const int drag_grip_avoid_padding = 0x7f06000d;
            
            public const int listMargins = 0x7f06000e;
            
            public const int listMarginsPadded = 0x7f06000f;
            
            public const int listNoDetailWidth = 0x7f060010;
            
            public const int list_item_min_size = 0x7f060011;
            
            public const int widget_item_min_size = 0x7f060012;
            
            public const int preference_screen_side_margin = 0x7f060013;
            
            public const int widget_margin = 0x7f060014;
            
            public const int widget_conf_preview_land_width = 0x7f060015;
            
            public const int widget_conf_preview_port_height = 0x7f060016;
            
            public const int layout_match_parent = 0x7f060017;
            
            public const int widget_conf_preview_width = 0x7f060018;
            
            public const int widget_conf_preview_height = 0x7f060019;
            
            public const int editor_side_margin = 0x7f06001a;
            
            public const int editor_vertical_margin = 0x7f06001b;
            
            public const int editor_vertical_margin_bottom = 0x7f06001c;
            
            public const int card_editor_shadow_bottom = 0x7f06001d;
            
            public const int card_editor_top_bottom = 0x7f06001e;
            
            public const int match_parent = 0x7f06001f;
            
            public const int wrap_content = 0x7f060020;
            
            public const int task_list_divider_height_small = 0x7f060021;
            
            public const int task_list_divider_height_large = 0x7f060022;
            
            public const int activity_lone_horizontal_margin = 0x7f060023;
            
            public const int activity_lone_vertical_margin = 0x7f060024;
            
            public const int activity_lone_horizontal_padding = 0x7f060025;
        }
        
        public sealed class Id
        {
            
            public const int ptr_content = 0x7f070038;
            
            public const int ptr_text = 0x7f070039;
            
            public const int ptr_progress = 0x7f07003a;
            
            public const int MvxBindingTagUnique = 0x7f07003b;
            
            public const int robotosans = 0x7f07003c;
            
            public const int robotocondensed = 0x7f07003d;
            
            public const int robotolight = 0x7f07003e;
            
            public const int robotothin = 0x7f07003f;
            
            public const int normal = 0x7f070040;
            
            public const int bold = 0x7f070041;
            
            public const int italic = 0x7f070042;
            
            public const int drawerLayout = 0x7f070043;
            
            public const int ptrLayout = 0x7f070044;
            
            public const int taskList = 0x7f070045;
            
            public const int taskListsDrawer = 0x7f070046;
            
            public const int taskDetails = 0x7f070047;
            
            public const int taskLists = 0x7f070048;
            
            public const int buttons = 0x7f070049;
            
            public const int list = 0x7f07004a;
            
            public const int zoom_full = 0x7f07004b;
            
            public const int editList = 0x7f07004c;
            
            public const int editText = 0x7f07004d;
            
            public const int delete = 0x7f07004e;
            
            public const int information = 0x7f07004f;
            
            public const int description_view = 0x7f070050;
            
            public const int description_edit = 0x7f070051;
            
            public const int editTextHost = 0x7f070052;
            
            public const int theTaskList = 0x7f070053;
            
            public const int textView = 0x7f070054;
            
            public const int theTaskListsList = 0x7f070055;
            
            public const int icon = 0x7f070056;
            
            public const int addEditText = 0x7f070057;
            
            public const int tllrTextView = 0x7f070058;
            
            public const int tllrEditText = 0x7f070059;
            
            public const int import_taskdconfig = 0x7f07005a;
            
            public const int hostname = 0x7f07005b;
            
            public const int port = 0x7f07005c;
            
            public const int organization = 0x7f07005d;
            
            public const int username = 0x7f07005e;
            
            public const int key = 0x7f07005f;
            
            public const int clientfile = 0x7f070060;
            
            public const int selectclient = 0x7f070061;
            
            public const int serverfile = 0x7f070062;
            
            public const int selectserver = 0x7f070063;
            
            public const int activity_menu_group = 0x7f070064;
            
            public const int menu_toggle_completed = 0x7f070065;
            
            public const int activity_listslist_menu_group = 0x7f070066;
            
            public const int drawer_menu_createlist = 0x7f070067;
            
            public const int menu_preferences = 0x7f070068;
            
            public const int action_refresh = 0x7f070069;
        }
        
        public sealed class Color
        {
            
            public const int viewpager_darkgrey = 0x7f080000;
            
            public const int viewpager_blue = 0x7f080001;
            
            public const int widgetItemBG_dark = 0x7f080002;
            
            public const int widgetItemBG_light = 0x7f080003;
            
            public const int listLightBG = 0x7f080004;
            
            public const int googlenow_grey = 0x7f080005;
            
            public const int googlenow_grey_trans = 0x7f080006;
            
            public const int googlenow_darkgrey = 0x7f080007;
            
            public const int googlenow_darkergrey = 0x7f080008;
            
            public const int googlenow_darkergrey_trans = 0x7f080009;
            
            public const int googlenow_darkgrey_shadow = 0x7f08000a;
            
            public const int background_holo_light = 0x7f08000b;
            
            public const int labelItemTextColorLight = 0x7f08000c;
            
            public const int labelItemTextColorDark = 0x7f08000d;
            
            public const int dragHandleColorLight = 0x7f08000e;
            
            public const int dragHandleColorDark = 0x7f08000f;
            
            public const int completedGrey = 0x7f080010;
            
            public const int mapTransLight = 0x7f080011;
            
            public const int uncheckedGrey = 0x7f080012;
            
            public const int start = 0x7f080013;
            
            public const int stop = 0x7f080014;
            
            public const int actionbar_text = 0x7f080015;
            
            public const int theme_yellow = 0x7f080016;
            
            public const int taskTextColor = 0x7f080017;
            
            public const int taskSecondaryTextColor = 0x7f080018;
        }
        
        public sealed class String
        {
            
            public const int title_create = 0x7f090000;
            
            public const int timemachine = 0x7f090001;
            
            public const int time = 0x7f090002;
            
            public const int done = 0x7f090003;
            
            public const int saved = 0x7f090004;
            
            public const int distance = 0x7f090005;
            
            public const int need_location_help = 0x7f090006;
            
            public const int near = 0x7f090007;
            
            public const int menu_save_and_add = 0x7f090008;
            
            public const int menu_delete = 0x7f090009;
            
            public const int menu_deletelist = 0x7f09000a;
            
            public const int menu_clearcompleted = 0x7f09000b;
            
            public const int menu_setdefaultlist = 0x7f09000c;
            
            public const int new_default_set = 0x7f09000d;
            
            public const int menu_managelists = 0x7f09000e;
            
            public const int add_item = 0x7f09000f;
            
            public const int delete_question = 0x7f090010;
            
            public const int delete_items_message = 0x7f090011;
            
            public const int delete_item_message = 0x7f090012;
            
            public const int delete_list_message = 0x7f090013;
            
            public const int editor_due_date_hint = 0x7f090014;
            
            public const int editor_title_hint = 0x7f090015;
            
            public const int editor_note_hint = 0x7f090016;
            
            public const int resolve_edit = 0x7f090017;
            
            public const int default_style = 0x7f090018;
            
            public const int show_items_as_tasks = 0x7f090019;
            
            public const int show_items_as_notes = 0x7f09001a;
            
            public const int sort_list_default = 0x7f09001b;
            
            public const int sort_list_alphabetical = 0x7f09001c;
            
            public const int sort_list_due = 0x7f09001d;
            
            public const int sort_list_updated = 0x7f09001e;
            
            public const int sort_list_manual = 0x7f09001f;
            
            public const int search_description = 0x7f090020;
            
            public const int archive = 0x7f090021;
            
            public const int view_deletedtasks = 0x7f090022;
            
            public const int location = 0x7f090023;
            
            public const int restore = 0x7f090024;
            
            public const int restore_to = 0x7f090025;
            
            public const int search_hint = 0x7f090026;
            
            public const int settings_theme = 0x7f090027;
            
            public const int settings_theme_dialog = 0x7f090028;
            
            public const int settings_lang = 0x7f090029;
            
            public const int settings_lang_dialog = 0x7f09002a;
            
            public const int settings_summary_theme_black = 0x7f09002b;
            
            public const int settings_summary_theme_dark = 0x7f09002c;
            
            public const int settings_summary_theme_light = 0x7f09002d;
            
            public const int settings_summary_theme_classic = 0x7f09002e;
            
            public const int settings_cat_appearance = 0x7f09002f;
            
            public const int preference_preview_text = 0x7f090030;
            
            public const int settings_account_title = 0x7f090031;
            
            public const int settings_account_summary = 0x7f090032;
            
            public const int settings_sync_enable_title = 0x7f090033;
            
            public const int gtasks_sync_info = 0x7f090034;
            
            public const int settings_cat_syncing = 0x7f090035;
            
            public const int gtasks = 0x7f090036;
            
            public const int show_from_all_lists = 0x7f090037;
            
            public const int lists = 0x7f090038;
            
            public const int deleted = 0x7f090039;
            
            public const int repeat = 0x7f09003a;
            
            public const int once = 0x7f09003b;
            
            public const int always = 0x7f09003c;
            
            public const int permission_read_label = 0x7f09003d;
            
            public const int permission_read_desc = 0x7f09003e;
            
            public const int permission_write_label = 0x7f09003f;
            
            public const int permission_write_desc = 0x7f090040;
            
            public const int settings_list_dialog = 0x7f090041;
            
            public const int settings_list = 0x7f090042;
            
            public const int drag_to_timetravel = 0x7f090043;
            
            public const int import_data_question = 0x7f090044;
            
            public const int import_started = 0x7f090045;
            
            public const int import_data_msg = 0x7f090046;
            
            public const int imported_result = 0x7f090047;
            
            public const int import_error = 0x7f090048;
            
            public const int showcase_main_title = 0x7f090049;
            
            public const int showcase_main_msg = 0x7f09004a;
            
            public const int showcase_drawer_title = 0x7f09004b;
            
            public const int showcase_drawer_msg = 0x7f09004c;
            
            public const int showcase_timemachine_title = 0x7f09004d;
            
            public const int showcase_timemachine_msg = 0x7f09004e;
            
            public const int donate_to_unlock = 0x7f09004f;
            
            public const int premiums_unlocked_and_thanks = 0x7f090050;
            
            public const int move = 0x7f090051;
            
            public const int move_to = 0x7f090052;
            
            public const int moved_x_to_list = 0x7f090053;
            
            public const int lock_note = 0x7f090054;
            
            public const int unlock_note = 0x7f090055;
            
            public const int locked = 0x7f090056;
            
            public const int unlocked = 0x7f090057;
            
            public const int password_required = 0x7f090058;
            
            public const int select_account = 0x7f090059;
            
            public const int password = 0x7f09005a;
            
            public const int password_set = 0x7f09005b;
            
            public const int password_cleared = 0x7f09005c;
            
            public const int passwords_dont_match = 0x7f09005d;
            
            public const int password_incorrect = 0x7f09005e;
            
            public const int enter_password = 0x7f09005f;
            
            public const int enter_new_password = 0x7f090060;
            
            public const int confirm_new_password = 0x7f090061;
            
            public const int apply = 0x7f090062;
            
            public const int clear_password = 0x7f090063;
            
            public const int password_info = 0x7f090064;
            
            public const int about = 0x7f090065;
            
            public const int sync_failed = 0x7f090066;
            
            public const int sync_login_failed = 0x7f090067;
            
            public const int changelog_full_title = 0x7f090068;
            
            public const int changelog_title = 0x7f090069;
            
            public const int completed = 0x7f09006a;
            
            public const int date_header_overdue = 0x7f09006b;
            
            public const int date_header_today = 0x7f09006c;
            
            public const int date_header_tomorrow = 0x7f09006d;
            
            public const int date_header_future = 0x7f09006e;
            
            public const int date_header_none = 0x7f09006f;
            
            public const int date_header_completed = 0x7f090070;
            
            public const int next_5_days = 0x7f090071;
            
            public const int next_n_days = 0x7f090072;
            
            public const int this_week = 0x7f090073;
            
            public const int please_select_note = 0x7f090074;
            
            public const int please_create_note = 0x7f090075;
            
            public const int hide_checkbox = 0x7f090076;
            
            public const int hide_checkbox_summary_on = 0x7f090077;
            
            public const int hide_checkbox_summary_off = 0x7f090078;
            
            public const int hide_completed = 0x7f090079;
            
            public const int hide_completed_summary_on = 0x7f09007a;
            
            public const int hide_completed_summary_off = 0x7f09007b;
            
            public const int hide_date = 0x7f09007c;
            
            public const int item_max_height = 0x7f09007d;
            
            public const int long_date_format = 0x7f09007e;
            
            public const int short_date_format = 0x7f09007f;
            
            public const int rows = 0x7f090080;
            
            public const int select_date = 0x7f090081;
            
            public const int localedefault = 0x7f090082;
            
            public const int donate = 0x7f090083;
            
            public const int donate_thanks = 0x7f090084;
            
            public const int hide_header = 0x7f090085;
            
            public const int transparency = 0x7f090086;
            
            public const int notes_shortcut = 0x7f090087;
            
            public const int shortcut_help1 = 0x7f090088;
            
            public const int loading_widget = 0x7f090089;
            
            public const int default_list = 0x7f09008a;
            
            public const int please_type_before_reminder = 0x7f09008b;
            
            public const int notecopied_one = 0x7f09008c;
            
            public const int notecopied_other = 0x7f09008d;
            
            public const int notecopied_zero = 0x7f09008e;
            
            public const int notecopied_two = 0x7f09008f;
            
            public const int notecopied_few = 0x7f090090;
            
            public const int notecopied_many = 0x7f090091;
            
            public const int notedeleted_one = 0x7f090092;
            
            public const int notedeleted_other = 0x7f090093;
            
            public const int notedeleted_zero = 0x7f090094;
            
            public const int notedeleted_two = 0x7f090095;
            
            public const int notedeleted_few = 0x7f090096;
            
            public const int notedeleted_many = 0x7f090097;
            
            public const int selected_one = 0x7f090098;
            
            public const int selected_other = 0x7f090099;
            
            public const int selected_zero = 0x7f09009a;
            
            public const int selected_two = 0x7f09009b;
            
            public const int selected_few = 0x7f09009c;
            
            public const int selected_many = 0x7f09009d;
            
            public const int background_sync = 0x7f09009e;
            
            public const int background_sync_info = 0x7f09009f;
            
            public const int sync_on_change = 0x7f0900a0;
            
            public const int sync_on_change_info = 0x7f0900a1;
            
            public const int sync_on_start = 0x7f0900a2;
            
            public const int sync_on_start_info = 0x7f0900a3;
            
            public const int sync_full_force = 0x7f0900a4;
            
            public const int sync_full_force_info = 0x7f0900a5;
            
            public const int snooze = 0x7f0900a6;
            
            public const int silent = 0x7f0900a7;
            
            public const int sound = 0x7f0900a8;
            
            public const int vibrate = 0x7f0900a9;
            
            public const int reminders = 0x7f0900aa;
            
            public const int standard = 0x7f0900ab;
            
            public const int notification_prio_high = 0x7f0900ac;
            
            public const int notification_prio_low = 0x7f0900ad;
            
            public const int priority = 0x7f0900ae;
            
            public const int notifications = 0x7f0900af;
            
            public const int dateformat_micro = 0x7f0900b0;
            
            public const int dateformat_weekday = 0x7f0900b1;
            
            public const int dateformat_short_1 = 0x7f0900b2;
            
            public const int dateformat_short_2 = 0x7f0900b3;
            
            public const int dateformat_short_3 = 0x7f0900b4;
            
            public const int dateformat_short_4 = 0x7f0900b5;
            
            public const int dateformat_long_1 = 0x7f0900b6;
            
            public const int dateformat_long_2 = 0x7f0900b7;
            
            public const int dateformat_just_date = 0x7f0900b8;
            
            public const int tasks = 0x7f0900b9;
            
            public const int all_tasks = 0x7f0900ba;
            
            public const int dashclock_tasks = 0x7f0900bb;
            
            public const int dashclock_restrict_to_tasks_in_a_specific_list = 0x7f0900bc;
            
            public const int dashclock_show_overdue_tasks = 0x7f0900bd;
            
            public const int dashclock_overdue_tasks_show = 0x7f0900be;
            
            public const int dashclock_overdue_tasks_hide = 0x7f0900bf;
            
            public const int dashclock_title_activity_tasks_settings = 0x7f0900c0;
            
            public const int dashclock_pref_header_general = 0x7f0900c1;
            
            public const int dashclock_due_upper_limit_title = 0x7f0900c2;
            
            public const int dashclock_today = 0x7f0900c3;
            
            public const int dashclock_tomorrow = 0x7f0900c4;
            
            public const int dashclock_next7 = 0x7f0900c5;
            
            public const int dashclock_anytime = 0x7f0900c6;
            
            public const int dashclock_will_show_as_many_as_possible = 0x7f0900c7;
            
            public const int dashclock_will_only_show_the_task_due_first = 0x7f0900c8;
            
            public const int dashclock_show_only_the_next_task = 0x7f0900c9;
            
            public const int dashclock_header_shown = 0x7f0900ca;
            
            public const int dashclock_first_task_shown = 0x7f0900cb;
            
            public const int dashclock_display_header = 0x7f0900cc;
            
            public const int editor = 0x7f0900cd;
            
            public const int bold = 0x7f0900ce;
            
            public const int italic = 0x7f0900cf;
            
            public const int normal = 0x7f0900d0;
            
            public const int title_style = 0x7f0900d1;
            
            public const int title_font = 0x7f0900d2;
            
            public const int body_font = 0x7f0900d3;
            
            public const int clickable_links = 0x7f0900d4;
            
            public const int small = 0x7f0900d5;
            
            public const int medium = 0x7f0900d6;
            
            public const int large = 0x7f0900d7;
            
            public const int text_size = 0x7f0900d8;
            
            public const int text = 0x7f0900d9;
            
            public const int add_a_reminder = 0x7f0900da;
            
            public const int backup = 0x7f0900db;
            
            public const int backup_import = 0x7f0900dc;
            
            public const int backup_export = 0x7f0900dd;
            
            public const int backup_import_msg = 0x7f0900de;
            
            public const int backup_export_msg = 0x7f0900df;
            
            public const int backup_import_success = 0x7f0900e0;
            
            public const int backup_file_not_found = 0x7f0900e1;
            
            public const int backup_import_failed = 0x7f0900e2;
            
            public const int backup_export_success = 0x7f0900e3;
            
            public const int backup_export_failed = 0x7f0900e4;
            
            public const int sd_card = 0x7f0900e5;
            
            public const int sd_card_sync = 0x7f0900e6;
            
            public const int sd_card_summary = 0x7f0900e7;
            
            public const int directory = 0x7f0900e8;
            
            public const int directory_summary = 0x7f0900e9;
            
            public const int dropbox = 0x7f0900ea;
            
            public const int dropbox_sync = 0x7f0900eb;
            
            public const int dropbox_sync_summary = 0x7f0900ec;
            
            public const int cannot_write_to_directory = 0x7f0900ed;
            
            public const int wait_for_dropbox = 0x7f0900ee;
            
            public const int pull_to_refresh_pull_label = 0x7f0900ef;
            
            public const int pull_to_refresh_release_label = 0x7f0900f0;
            
            public const int pull_to_refresh_refreshing_label = 0x7f0900f1;
            
            public const int app_name = 0x7f0900f2;
            
            public const int account_type = 0x7f0900f3;
            
            public const int ok = 0x7f0900f4;
            
            public const int menu_toggle_completed = 0x7f0900f5;
            
            public const int menu_createlist = 0x7f0900f6;
            
            public const int menu_preferences = 0x7f0900f7;
            
            public const int menu_share = 0x7f0900f8;
            
            public const int settings_general = 0x7f0900f9;
            
            public const int settings_debug = 0x7f0900fa;
            
            public const int settings_edit_accounts = 0x7f0900fb;
            
            public const int settings_network_logging = 0x7f0900fc;
            
            public const int settings_network_logging_enabled = 0x7f0900fd;
            
            public const int settings_network_logging_disabled = 0x7f0900fe;
            
            public const int editaccount_servername = 0x7f0900ff;
            
            public const int editaccount_serverport = 0x7f090100;
        }
        
        public sealed class Plurals
        {
            
            public const int notecopied_msg = 0x7f0a0000;
            
            public const int notedeleted_msg = 0x7f0a0001;
            
            public const int mode_choose = 0x7f0a0002;
        }
        
        public sealed class Style
        {
            
            public const int ViewPagerStyleDarkGrey = 0x7f0b0000;
            
            public const int ViewPagerStyleDarkTransparent = 0x7f0b0001;
            
            public const int FragmentHint = 0x7f0b0002;
            
            public const int EditorLayoutStyle = 0x7f0b0003;
            
            public const int EditorTextStyle = 0x7f0b0004;
            
            public const int ActionBarDropDownItem_Dark = 0x7f0b0005;
            
            public const int ActionBarDropDownItem_Light = 0x7f0b0006;
            
            public const int TaskListItemBlack = 0x7f0b0007;
            
            public const int TaskListItemDark = 0x7f0b0008;
            
            public const int TaskListItemLight = 0x7f0b0009;
            
            public const int TaskListItemLightClassic = 0x7f0b000a;
            
            public const int ListMarginStyleCard = 0x7f0b000b;
            
            public const int ListMarginStyleClassic = 0x7f0b000c;
            
            public const int ListSpaceDividerStyle = 0x7f0b000d;
            
            public const int ListNarrowDividerStyle = 0x7f0b000e;
            
            public const int ListOnePxDividerStyle = 0x7f0b000f;
            
            public const int PullToRefreshStyle = 0x7f0b0010;
            
            public const int DashClockSettings_Theme_Base = 0x7f0b0011;
            
            public const int DashClockSettings_Theme = 0x7f0b0012;
            
            public const int DashClockSettings_ActionBar = 0x7f0b0013;
            
            public const int DashClockSettings_ActionButton_Overflow = 0x7f0b0014;
            
            public const int GreyableButtonToggle = 0x7f0b0015;
            
            public const int Widget_PullToRefresh_ProgressBar_Horizontal_Center = 0x7f0b0016;
            
            public const int MyActionBar = 0x7f0b0017;
            
            public const int TitleTextStyle = 0x7f0b0018;
            
            public const int TabTextStyle = 0x7f0b0019;
            
            public const int ThemeNinjaTasks = 0x7f0b001a;
            
            public const int TaskListsListStyleLight = 0x7f0b001b;
            
            public const int TaskListsListRowStyleLight = 0x7f0b001c;
            
            public const int TaskListsListRowSecondaryStyleLight = 0x7f0b001d;
            
            public const int TaskListStyleLight = 0x7f0b001e;
            
            public const int ThemeHoloLightDarkActionBar = 0x7f0b001f;
            
            public const int ThemeSplash = 0x7f0b0020;
        }
        
        public sealed class Menu
        {
            
            public const int activity_main = 0x7f0c0000;
            
            public const int SelectRemoteDeviceActions = 0x7f0c0001;
        }
        
        public sealed class Styleable
        {
            
            public sealed class PullToRefreshHeader
            {
                
                public const int ptrHeaderBackground = 0;
                
                public const int ptrHeaderHeight = 1;
                
                public const int ptrHeaderTitleTextAppearance = 2;
                
                public const int ptrProgressBarColor = 3;
                
                public const int ptrPullText = 4;
                
                public const int ptrRefreshingText = 5;
                
                public const int ptrReleaseText = 6;
                
                public static readonly int[] AllIds = new[] { R.Attr.ptrHeaderBackground, R.Attr.ptrHeaderHeight, R.Attr.ptrHeaderTitleTextAppearance, R.Attr.ptrProgressBarColor, R.Attr.ptrPullText, R.Attr.ptrRefreshingText, R.Attr.ptrReleaseText };
            }
            
            public sealed class SeekBarPreference
            {
                
                public const int max = 0;
                
                public const int min = 1;
                
                public const int unitsLeft = 2;
                
                public const int unitsRight = 3;
                
                public const int units = 4;
                
                public const int summary = 5;
                
                public const int interval = 6;
                
                public static readonly int[] AllIds = new[] { R.Attr.max, R.Attr.min, R.Attr.unitsLeft, R.Attr.unitsRight, R.Attr.units, R.Attr.summary, R.Attr.interval };
            }
            
            public sealed class StyledTextView
            {
                
                public const int linkify = 0;
                
                public const int styledText = 1;
                
                public const int titleRelativeSize = 2;
                
                public const int titleFontFamily = 3;
                
                public const int titleFontStyle = 4;
                
                public const int bodyFontFamily = 5;
                
                public const int secondaryColor = 6;
                
                public static readonly int[] AllIds = new[] { R.Attr.linkify, R.Attr.styledText, R.Attr.titleRelativeSize, R.Attr.titleFontFamily, R.Attr.titleFontStyle, R.Attr.bodyFontFamily, R.Attr.secondaryColor };
            }
            
            public sealed class GreyableToggleButton
            {
                
                public const int secondaryColor = 0;
                
                public static readonly int[] AllIds = new[] { R.Attr.secondaryColor };
            }
            
            public sealed class FilePickerTheme
            {
                
                public const int isDialog = 0;
                
                public static readonly int[] AllIds = new[] { R.Attr.isDialog };
            }
            
            public sealed class MvxBinding
            {
                
                public const int MvxBind = 0;
                
                public const int MvxLang = 1;
                
                public static readonly int[] AllIds = new[] { R.Attr.MvxBind, R.Attr.MvxLang };
            }
            
            public sealed class MvxControl
            {
                
                public const int MvxTemplate = 0;
                
                public static readonly int[] AllIds = new[] { R.Attr.MvxTemplate };
            }
            
            public sealed class MvxListView
            {
                
                public const int MvxItemTemplate = 0;
                
                public const int MvxDropDownItemTemplate = 1;
                
                public static readonly int[] AllIds = new[] { R.Attr.MvxItemTemplate, R.Attr.MvxDropDownItemTemplate };
            }
            
            public sealed class MvxExpandableListView
            {
                
                public const int GroupItemTemplate = 0;
                
                public static readonly int[] AllIds = new[] { R.Attr.GroupItemTemplate };
            }
            
            public sealed class MvxImageView
            {
                
                public const int MvxSource = 0;
                
                public static readonly int[] AllIds = new[] { R.Attr.MvxSource };
            }
        }
    }
}
