#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18449
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NinjaTasks.App.Droid.Resource", IsApplication=true)]

namespace NinjaTasks.App.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AutoMapper.Android.Resource.String.ApplicationName = global::NinjaTasks.App.Droid.Resource.String.ApplicationName;
			global::AutoMapper.Android.Resource.String.Hello = global::NinjaTasks.App.Droid.Resource.String.Hello;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.ApplicationName = global::NinjaTasks.App.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.Hello = global::NinjaTasks.App.Droid.Resource.String.Hello;
			global::NinjaTools.Droid.Resource.Attribute.GroupItemTemplate = global::NinjaTasks.App.Droid.Resource.Attribute.GroupItemTemplate;
			global::NinjaTools.Droid.Resource.Attribute.MvxBind = global::NinjaTasks.App.Droid.Resource.Attribute.MvxBind;
			global::NinjaTools.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::NinjaTasks.App.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::NinjaTools.Droid.Resource.Attribute.MvxItemTemplate = global::NinjaTasks.App.Droid.Resource.Attribute.MvxItemTemplate;
			global::NinjaTools.Droid.Resource.Attribute.MvxLang = global::NinjaTasks.App.Droid.Resource.Attribute.MvxLang;
			global::NinjaTools.Droid.Resource.Attribute.MvxSource = global::NinjaTasks.App.Droid.Resource.Attribute.MvxSource;
			global::NinjaTools.Droid.Resource.Attribute.MvxTemplate = global::NinjaTasks.App.Droid.Resource.Attribute.MvxTemplate;
			global::NinjaTools.Droid.Resource.Id.MvxBindingTagUnique = global::NinjaTasks.App.Droid.Resource.Id.MvxBindingTagUnique;
			global::NinjaTools.Droid.Resource.Styleable.MvxBinding = global::NinjaTasks.App.Droid.Resource.Styleable.MvxBinding;
			global::NinjaTools.Droid.Resource.Styleable.MvxBinding_MvxBind = global::NinjaTasks.App.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::NinjaTools.Droid.Resource.Styleable.MvxBinding_MvxLang = global::NinjaTasks.App.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::NinjaTools.Droid.Resource.Styleable.MvxControl = global::NinjaTasks.App.Droid.Resource.Styleable.MvxControl;
			global::NinjaTools.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::NinjaTasks.App.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::NinjaTools.Droid.Resource.Styleable.MvxExpandableListView = global::NinjaTasks.App.Droid.Resource.Styleable.MvxExpandableListView;
			global::NinjaTools.Droid.Resource.Styleable.MvxExpandableListView_GroupItemTemplate = global::NinjaTasks.App.Droid.Resource.Styleable.MvxExpandableListView_GroupItemTemplate;
			global::NinjaTools.Droid.Resource.Styleable.MvxImageView = global::NinjaTasks.App.Droid.Resource.Styleable.MvxImageView;
			global::NinjaTools.Droid.Resource.Styleable.MvxImageView_MvxSource = global::NinjaTasks.App.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::NinjaTools.Droid.Resource.Styleable.MvxListView = global::NinjaTasks.App.Droid.Resource.Styleable.MvxListView;
			global::NinjaTools.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::NinjaTasks.App.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::NinjaTools.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::NinjaTasks.App.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int GroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080002
			public const int actionbar_text = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int start = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int stop = 2131230721;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070001
			public const int activity_horizontal_margin = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int activity_vertical_margin = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background = 2130837509;
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash_non_stretch = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ui_bluetooth_proxy = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ui_refresh = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int action_refresh = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int buttons = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int clientfile = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int contentFrame = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int hostname = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int import_taskdconfig = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int information = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int key = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int list = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int organization = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int port = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int selectclient = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int selectserver = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int serverfile = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int username = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int zoom_full = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConfigureAccounts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Container = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LogEntry = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SelectRemoteDeviceItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SelectRemoteDeviceView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TaskWarriorAccountView = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int SelectRemoteDeviceActions = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int account_type = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int editaccount_servername = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int editaccount_serverport = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int settings_debug = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int settings_edit_accounts = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int settings_general = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int settings_network_logging = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int settings_network_logging_disabled = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int settings_network_logging_enabled = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int MyActionBar = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int TabTextStyle = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int ThemeNinjaTasks = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int ThemeSplash = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int TitleTextStyle = 2131296257;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int account_authenticator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int account_prefs = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int general_settings = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int sync_ninjatasks = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int sync_nonsenseapps_notepad = 2130968580;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_GroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
